---
name: IO-CaptureOutput
version: 1.08_50
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: 'capture STDOUT and STDERR from Perl code, subprocesses or XS'
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dagolden.googlecode.com/svn/
requires:
  Carp: 0
  Exporter: 0
  File::Basename: 0
  File::Temp: 0.16
  Symbol: 0
build_requires:
  File::Spec: 3.27
  IO::File: 0
  Test::More: 0.62
provides:
  IO::CaptureOutput:
    file: lib/IO/CaptureOutput.pm
    version: 1.08_50
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
