---
name: IO-CaptureOutput
version: 1.04_03
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: 'capture STDOUT and STDERR from Perl code, subprocesses or XS'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Temp: 0.16
build_requires:
  Test::More: 0.62
provides:
  IO::CaptureOutput:
    file: lib/IO/CaptureOutput.pm
    version: 1.04_03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
